version: '3.8'

services:
  mcp-package-manager:
    build: .
    container_name: mcp-package-manager
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      # Mount for persistent cache (optional)
      - cache-data:/app/cache
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mcp-package-manager.rule=Host(`mcp-package-manager.yourdomain.com`)"
      - "traefik.http.routers.mcp-package-manager.tls=true"
      - "traefik.http.routers.mcp-package-manager.tls.certresolver=letsencrypt"

volumes:
  cache-data: