# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:20-alpine AS builder
WORKDIR /app

# Install dependencies and build
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm install --ignore-scripts && npm run build

# Production image
FROM node:20-alpine
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install --production --ignore-scripts
COPY --from=builder /app/dist ./dist

EXPOSE 3000
ENTRYPOINT ["node", "dist/index.js"]
