[build]
  publish = "public"
  functions = "netlify/functions"
  command = "echo 'Using pre-built JavaScript functions - no build required'"

[functions]
  node_bundler = "nft"

[functions."*"]
  timeout = 10

# Function routes
[[redirects]]
  from = "/mcp"
  to = "/.netlify/functions/mcp"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/analytics"
  to = "/.netlify/functions/analytics"
  status = 200

[[redirects]]
  from = "/api/analytics-data"
  to = "/.netlify/functions/analytics?data=true"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# CORS for MCP endpoints
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[context.production.environment]
  NODE_ENV = "production"