name: Deploy to MCP Hosting Service

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Build project
      run: npm run build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Deploy to MCP Hosting Service
      env:
        MCP_API_KEY: ${{ secrets.MCP_API_KEY }}
        MCP_HOSTING_API: ${{ secrets.MCP_HOSTING_API || 'https://api.mcp-hosting.com' }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: node deploy-to-hosting.js
    
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## What's Changed
          - Auto-deployment to MCP Hosting Service
          - Available at: https://api.mcp-hosting.com/mcp/javascript-package-manager
          
          ## Configuration
          ```json
          {
            "mcpServers": {
              "javascript-package-manager": {
                "transport": "http",
                "url": "https://api.mcp-hosting.com/mcp/javascript-package-manager"
              }
            }
          }
          ```
        draft: false
        prerelease: false